import {
  Home,
  Images,
  Library,
  Settings,
  User,
  Shield,
} from "lucide-react";

export const navigationItems = [
  {
    href: "/",
    location: "/",
    classicLabel: "System Feed",
    loungeLabel: "Front Shelf",
    motionLabel: "Discover",
    detail: "Discover public-domain books and open knowledge.",
    code: "01",
    icon: Home,
  },
  {
    href: "/infinite",
    location: "/infinite",
    classicLabel: "Open Gallery",
    loungeLabel: "Artwork Wander",
    motionLabel: "Visual Field",
    detail: "Drift through public-domain and CC0 artwork.",
    code: "02",
    icon: Images,
  },
  {
    href: "/library",
    location: "/library",
    classicLabel: "Archive",
    loungeLabel: "Reading Collection",
    motionLabel: "The Archive",
    detail: "Return to saved books, bookmarks, and history.",
    code: "03",
    icon: Library,
  },
  {
    href: "/profile",
    location: "/profile",
    classicLabel: "Profile",
    loungeLabel: "Reader Card",
    motionLabel: "Reader Signal",
    detail: "Identity, sync status, and account memory.",
    code: "04",
    icon: User,
  },
  {
    href: "/settings",
    location: "/settings",
    classicLabel: "Settings",
    loungeLabel: "Room Controls",
    motionLabel: "Preferences",
    detail: "Theme, reader behavior, and source controls.",
    code: "05",
    icon: Settings,
  },
  {
    href: "/legal",
    location: "/legal",
    classicLabel: "Legal",
    loungeLabel: "House Rules",
    motionLabel: "About",
    detail: "Usage terms, privacy, and content policies.",
    code: "06",
    icon: Shield,
  },
] as const;
